project:
  type: website

website:
  title: "JIYEON.Data"
  navbar:
    left:
      - href: about.qmd
        text: About
      - href: f1_data
        text: Formula1
      - href: posts
        text: Posts
      
    right: 
      - icon: linkedin
        text: LinkedIn
        url: https://www.linkedin.com/in/jiyeon-k-088823157/
      - icon: github
        text: Github
        url: https://github.com/jiyeon0822/jiyeon.github.io
      - text: "{{< fa envelope >}} Email"
        url: mailto:jiyeon910822@gmail.com

format:
  html:
    theme:
      - cosmo
      - theme.scss
      - anari_custom.scss
    toc: true



